### ISSUE TITLE
Страница всех спектаклей

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#1]
- [x] верстка и анимации ([макет](https://www.figma.com/file/xockMwJFRcDaGT5c9B0nmO/Luna-Main?node-id=0%3A1&t=UkvxCUjQV4LMWK92-0))
    - [x] десктопная версии
    - [x] мобильная версии
    - [x] анимация нажатия кнопок [как здесь](https://mui.com/material-ui/react-button/#outlined-buttons), можно даже затащить оттуда
    - [x] [анимация hover для картинок](https://codepen.io/futenma/pen/mdPZoXN)

- [x] запросы к бэку

   общий формат фильтрации: ```GET /api/:pluralApiId?filters[field][operator]=value```
    - [x] фильтровать спектакли для детей: ```filters[rating][$lt]=16```
    - [x] фильтровать премьеры: ```filters[isPremiere][$eq]=true```
    - [x] фильтровать зал: : ```filters[scene][$eq]=Зал "Маленькая Луна"```
    - [x] поиск: ```filters[title][$contains]=текст```

--- 
**Дедлайн**:   30.11 вечер (20-21)

**Comment by demig00d** [comment]
Замечания дизайнера:
- [ ]  в сценах (фильтр) шрифт не arial, а Montserrat. Еще я меняла фильтры немного, посмотри в макете, пожалуйста
- [ ]   в фильтрах и в карточках спектаклей «маленькая луна» в таких кавычках. Вообще, везде, где увидите, кавычки елочками должны быть
- [ ]   по хорошему, в карточках надо союзы и имена переносить на след строчку, но это вроде не ваша работа уже
- [ ]   в карточках нужно поправить расстояние между заголовком и описанием
- [ ]   точно сказать не могу, может так отображается просто, но цвет премьеры немного не такой, как у меня в макетах, проверь, пожалуйста
- [ ]   в карточках и в фильтрах я писала не большой и малый зал, а сцены

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/8954808736f736e793d3064fa1b1351e5fcc5148

**Comment by demig00d** [comment]
- [ ] при нажатии на строку поиска вот такая штука выходит (1 скрин)
- [ ] карточки спектаклей не посередине относительно ширины экрана, можно ли что-то с этим сделать? (2 скрин)
- [ ] в карточках нужно сделать выравнивание кнопок по нижней границе, чтобы ровно все было
- [ ] теперь очень долгая анимация у кнопок в карточках)) и не плавная, как в хедере, например + нужна плавнее и анимация при наведении на заголовок карточки


![image](https://user-images.githubusercontent.com/28487425/209336898-162ad32f-b202-4bfb-9342-4b56fd0386a7.png)

![image](https://user-images.githubusercontent.com/28487425/209336906-7d02e4c2-b959-46b4-8e1b-804892a116a6.png)

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/0fa73d995a204b8dcff61f00cd26206cabba19cd
