### ISSUE TITLE
HTML вместо markdown

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#121]
сейчас на соответствующих страницах используется плагин для react-markdown, но встроенное видео не отображается, да и сам markdown не нужен:
- [x] описание спектакля
- [x] описание новости
- [x] контакты
- [x] описание персоны

**Comment by demig00d** [comment]
пример текста новостей ```/api/articles/3```

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/404976d56321eaa99fc14ecf4a8584575b1a585a
