### ISSUE TITLE
Выравнивание слайдеров спектаклей

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#122]
- [x] карточки спектаклей на главной
- [x] карточки спектаклей на других страницах

![photo_2023-01-03_16-23-31](https://user-images.githubusercontent.com/28487425/210366815-ad87b51b-7516-4798-915b-18ca219f92d8.jpg)
![photo_2023-01-03_16-23-31 (2)](https://user-images.githubusercontent.com/28487425/210366800-e138b742-9305-4734-bddd-3dbc3de31b97.jpg)
![photo_2023-01-03_16-23-31 (3)](https://user-images.githubusercontent.com/28487425/210366813-1bfcd984-b76b-41f8-98ce-03a2b6abd536.jpg)
![photo_2023-01-03_16-29-15](https://user-images.githubusercontent.com/28487425/210366817-4708eb0f-202f-4401-ac24-5b0d7a99a90d.jpg)

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/2d0887cfe80000d8c672e7b7b6a19a5ca7b7f743

**Comment by demig00d** [comment]
есть ещё слайдер на странице актёра, к примеру /persons/1, при этом если спектакль один как здесь /person/3 - его сдвигать не надо
