### ISSUE TITLE
Главная: Поставить новые шторы 

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#123]
Добавить [шторы](https://www.figma.com/file/iFD77wEGzvflypceaAviSo/Untitled?node-id=0%3A10&t=82MU437ozbbtGZQw-0), скорректированные дизайнером

<img width="354" alt="Screenshot 2023-01-03 at 16 36 26" src="https://user-images.githubusercontent.com/28487425/210367821-25c5fdb0-5ccb-468f-85bd-edfbe188999b.png">

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/d2fd9b16e122fe6e529dbcfaf01b7e398fe14b9a
