### ISSUE TITLE
Мобильная Главная: Сделать новости как на макете 

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#125]
- [x] 3 элемента вместо 4-х
- [x] заголовок больше и жирнее

то есть как [здесь](https://www.figma.com/file/iFD77wEGzvflypceaAviSo/Untitled?node-id=24%3A34&t=82MU437ozbbtGZQw-0):

<img width="398" alt="Screenshot 2023-01-03 at 16 26 08" src="https://user-images.githubusercontent.com/28487425/210375415-d21e404c-546c-4ba4-98d9-225565785e57.png">

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/9ab27e5fecdc58b6cb1f9f24e514b4f839353c1a
