### ISSUE TITLE
Мобильная Главная: зафиксировать положение рейтинга 

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#126]
Сделать рейтинг фиксированным, как на макете

https://user-images.githubusercontent.com/28487425/210390307-4a4ded60-7d86-4131-890c-32027caf85f1.mov

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/64d042c642c94ebff6deb23e3ab3c30ca27be124
