### ISSUE TITLE
Мобильные Спектакли: индикатор слайдера в комментариях наезжает на текст

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#127]
Индикатор слайдера в комментариях наезжает на текст при нажатие "развернуть польностью":

/play/4:

https://user-images.githubusercontent.com/28487425/210392794-4a4fde9a-40c0-436d-b29c-b1663eeda50a.mov

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/ef5a2245a67fd2bc007f339e86116ae7eadf9511
