### ISSUE TITLE
Убрать надпись "спектакль"

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#129]
Это изменение есть в [макете](https://www.figma.com/file/iFD77wEGzvflypceaAviSo/Untitled?node-id=0%3A10&t=9xvdsT5tcBQ7FzVa-0)

Убрать надпись "спектакль"
- [x] на слайдере в главной
- [x] на обложке на странице спектакля

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/aba77cc951b00efefeab690585b31504d6c5cf90
