### ISSUE TITLE
Страница отдельного спектакля

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#13]
В макетах называется ["спектакль"](https://www.figma.com/file/xockMwJFRcDaGT5c9B0nmO/Luna-Main?node-id=113%3A923&t=Cop6H7NP6P2nbyNQ-0)

ToDo:
  - [x] верстка: десктопная версия
  - [x] верстка: мобильная версия
  - [x] анимация при наведении на картинки актёров и картинки галереи как тут [new.lunatheatre.ru/plays](http://new.lunatheatre.ru/plays)https://github.com/tribble-io/luna/blob/24bd0fe2c27df2ba2993e531b7942cf8ceaa2f32/src/components/showsCards/shows.module.scss#L91
  - [x] брать данные для афиши следующим образом: ```/api/shows?filters[date][$gte]=<сегодня>&sort[0]=date&filters[play][id][$eq]=<id спектакля>&populate=play```
  - [x] под афишей опциональный элемент c пушкинской картой,  у сущности ```play``` **теперь есть** поле ```isPushkinCard```<img width="300" alt="Screenshot 2022-12-04 at 11 49 18" src="https://user-images.githubusercontent.com/28487425/205481961-4489b3f0-4d93-48c9-8c57-d9df89e94e1a.png">
  - [x] сделать раздел с актёрами в виде компонента (url: нужно добавить в параметр populate значение ```roles.actors```)
  - [x] раздел с актёрами нужно сделать в виде компонента (url: нужно добавить в параметр populate значение ```roles.actors```)
  - [x] раздел упоминания в прессе, у сущности ```play``` **теперь есть** новое поле ```press```,
  - [x] в разделе "фотографии со спектакля": использовать этот компонент https://github.com/tribble-io/luna/tree/main/src/components/photoSlider , у сущности ```play``` **теперь есть** новое поле ```galery```, из которого брать фотки (url: нужно добавить в параметр populate значение ```gallery```)

---
**дедлайн**: вторник (6.12)

**Comment by demig00d** [comment]
Замечания дизайнера:
- [ ] в сценах (фильтр) шрифт не arial, а Montserrat. Еще я меняла фильтры немного, посмотри в макете, пожалуйста
- [ ] в фильтрах и в карточках спектаклей «маленькая луна» в таких кавычках. Вообще, везде, где увидите, кавычки елочками должны быть
- [ ] по хорошему, в карточках надо союзы и имена переносить на след строчку, но это вроде не ваша работа уже
- [ ] в карточках нужно поправить расстояние между заголовком и описанием
- [ ] точно сказать не могу, может так отображается просто, но цвет премьеры немного не такой, как у меня в макетах, проверь, пожалуйста
- [ ] в карточках и в фильтрах я писала не большой и малый зал, а сцены

**Comment by demig00d** [comment]
- [ ] #63
- [ ] #64 
- [ ] #65
- [ ] #41

**Comment by demig00d** [comment]
- [ ] на 1 экране очень долгая анимация у кнопки и не плавная, как в хедере, например
- [ ] в блоке пресса, не отображается число с пагинацией (в firefox и safari)
- [ ] в блоке галереи не работают стрелки (в firefox и safari)
- [ ] на этой странице в блоке оставления отзыва под формой чекбокс одного вида, а на других страницах другой был (в активном положении). надо тогда везде этот чекбокс сделать такого вида, как на этой странице
- [ ] в блоке оставления отзыва перенести выше «я не робот», как в макете

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/a8646ea47d5193862e4bb65733d773286fdb5668

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/2bf79348f89b62d3e93b3a12647ac22acb643929 - slider fix
