### ISSUE TITLE
Поменять галочку на странице новости

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#131]
В разделе подписаться на рассылку, что внизу страницы отдельной новости нужно поменять картинку галочки:

как сейчас vs как надо (взято со страницы спектакля)
<img width="300" alt="Screenshot 2023-01-04 at 07 28 42" src="https://user-images.githubusercontent.com/28487425/210485650-4f4855ca-44b9-4a75-b1e1-fca52938c15e.png"> <img width="300" alt="Screenshot 2023-01-04 at 07 28 35" src="https://user-images.githubusercontent.com/28487425/210485630-08757259-9f8e-4f78-b2d0-acd4e8f25e19.png">

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/e9ef60022ca80c3b0cb173feabbda8037e5029b6
