### ISSUE TITLE
Скроллить до блока о спектакле при переходе с большого слайдера на главной

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#138]
Нужно чтобы страница спектакля открывалась без прогрузки обложки (т.е. чтобы та отображалась моментально), а затем скроллить до описания под обложкой

перед этим нужно [поправить аспект обложки](#130)

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/1a3e0eaa98a93bbe5bac5313ba4c31478d703b58
