### ISSUE TITLE
Страница все новости: выровнять месяца и икону календаря

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#141]
на картинках ниже видно что месяца (или мб иконки) расположены криво, сделать как на [макете](https://www.figma.com/file/tljc3lgdVBKnMoBeg0UHg5/Luna-theatre?node-id=0%3A1&t=9xvdsT5tcBQ7FzVa-0)
![photo_2023-01-04_09-05-51 (2)](https://user-images.githubusercontent.com/28487425/210494408-86e4067e-b976-4305-9119-129d914161c5.jpg)
![photo_2023-01-04_09-05-51](https://user-images.githubusercontent.com/28487425/210494411-4db15042-7679-44b0-b266-9fbeaf271c26.jpg)

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/67129b02a08306d8ac5094c88a83e5a793f22a48
