### ISSUE TITLE
Страница партнеры

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#144]
десктопная версия сильно похожа на страницу партнеров со [старого сайта](http://www.lunatheatre.ru/pages/nashi-partnery)
шакальный макет: [вот](https://www.figma.com/file/iFD77wEGzvflypceaAviSo/Untitled?node-id=0%3A1&t=9xvdsT5tcBQ7FzVa-0)
endpoint: ```/api/partner?populate=partner.logo```

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/tree/issues-fix-144
