### ISSUE TITLE
Труппа: перенести "приглашенные артисты" в чекбокс

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#148]
<img width="600" alt="Screenshot 2023-01-04 at 15 10 36" src="https://user-images.githubusercontent.com/28487425/210552449-e4134ca1-ab1e-4f01-b8e2-358eb98475b1.png">

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/3a3279d5ae0070dd9d7f55da11d5fc58439ce0c5
