### ISSUE TITLE
Добавить отступ сверху в стиль для встроенного видео

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#154]
Отступ сверху должен быть симметричен уже имеющемся отступу снизу, 
вот страницы, на которых бывают видео:
- [x] описание спектакля
- [x] описание новости
- [x] контакты
- [x] описание персоны

На скриншоте выделено место, где не хватает отступа:

![photo_2023-01-08_00-53-54](https://user-images.githubusercontent.com/28487425/211171640-7f25d52c-2011-4a22-b873-7c70c1e3c692.jpg)

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/tree/issues-fix-154
