### ISSUE TITLE
Добавить стиль для списка страниц в карте сайта

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#155]
как список выглядит сейчас:

<img width="510" alt="Screenshot 2023-01-08 at 00 58 24" src="https://user-images.githubusercontent.com/28487425/211171754-03d9a6ad-84f3-4324-b5b7-4fb8ad9ed119.png">

как примерно должен выглядеть (точки слева у каждого пункта оставить с текущей версии, но поменять цвет):

<img width="510" alt="Screenshot 2023-01-08 at 00 58 24" src="https://user-images.githubusercontent.com/28487425/211171839-c14e60f9-425b-4794-8e9b-b417f797294b.jpg">

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/tree/issues-fix-155
