### ISSUE TITLE
Страница персоны

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#167]
- [x] #166 
- [x] ограничить количество выступлений (как на макете)
- [x] сортировать кино в порядке убывания
- [x] пофиксить даты выступлений
<img width="505" alt="Screenshot 2023-01-12 at 11 43 14" src="https://user-images.githubusercontent.com/28487425/212024112-c5614b27-7a25-47d2-a64b-7bfced1b8ddf.png">

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/94d3c1937ba188e6c64946aa739d1b4caa0fdda8
