### ISSUE TITLE
Sticky шапка должна останавливаться до подвала

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#171]
Сейчас шапка перекрывает подвал

![Image](https://user-images.githubusercontent.com/28487425/216576149-23b3d575-7680-4e0d-84d0-fb3cc9968ae2.jpg)

нужно чтобы она останавливалась примерно на таком расстоянии

![Image](https://user-images.githubusercontent.com/28487425/216576350-a6f75e9e-5ed4-45f4-82fe-cd133a69734d.png)

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/11de8d545c94090977ec6f0608ad7ef13ab7fa23

**Comment by demig00d** [comment]
> 11de8d5

Не совсем то, в твоем варианте шапка просто скрывается за подвал, и на некоторых страницах не работает (страница "контакты" например)

Нужно чтобы шапка как бы "вытеснялась" подвалом, как даты на страницы премии ромашка, реально ли так сделать?
