### ISSUE TITLE
Мобильная главная: сократить отступ между месяцем и красным линейным календарём

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#176]
Нужно убрать 100 пикселей между месяцем и линейным календарём 

![photo_2023-02-01_22-47-57](https://user-images.githubusercontent.com/28487425/216147938-64453cbe-bc51-4e7a-9e08-dcedbb525b20.jpg)

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/43c1ff1ce6200c9bbf7537ec5171031a8fb1d035
