### ISSUE TITLE
Фон мобильной версии: полоса снизу

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#179]
![photo_2023-02-01_23-03-26](https://user-images.githubusercontent.com/28487425/216178512-5dca5d63-4f7f-42be-b84f-716555235f81.jpg)

**Comment by demig00d** [comment]
по идее, перенос фона из тэга body в html убирает полосу, но нужно сохранить текущее расположение градиента

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/tree/fix-issues-179
