### ISSUE TITLE
Сместить вниз текст на обложке спектакля

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#180]
Изменения нужны для десктопных версий
- [x] на главной
- [x] на странице спектакля

![Image](https://user-images.githubusercontent.com/28487425/216561384-8cdbec1a-81aa-4c05-ba98-ee9f75d240c8.jpg)

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/1f044d5d8b8e5bb04f74ac8d57ceb3ce4341aa77
