### ISSUE TITLE
Мобильная главная, основной слайдер: переместить кнопку "билеты", а надпись уменьшить и сдвинуть вниз

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#197]
- [x] переместить кнопку "билеты" под слайдер, 
- [x] рейтинг перенести в кнопку справа от надписи "билеты"
- [x] весь остальной текст на слайдере уменьшить и сдвинуть вниз

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/tree/fix-issues-197
