### ISSUE TITLE
Сделать чтобы баннер ввел на страницу Герасимова при клике

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#203]
ссылка на страницу Герасимова ```/person/35```

сам баннер выделен на скриншоте:
![photo_2023-03-02_16-37-57](https://user-images.githubusercontent.com/28487425/222444185-99bb77f6-eb98-43f9-b437-f5436df69331.jpg)

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/tree/fix-issues-202
