### ISSUE TITLE
Страница премии ромашка

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#28]
[макет](https://www.figma.com/file/tljc3lgdVBKnMoBeg0UHg5/Luna-theatre?node-id=800%3A1406&t=R33FapXLV5pl4PUO-0), фотки пока оставляем цветные, замечания от дизайнера буду стараться добавлять сюда

**так выглядит запрос**: ```/api/romaska-awards?populate=plays.role.actor.cover&sort=year:desc```

---
**дедлайн**: 13.12

**Comment by demig00d** [comment]
Замечания дизайнера
- [ ] в тексте в начале страницы «театр луны» и «ромашка» тоже в таких кавычках (:
- [ ] в карточках в названиях спектаклей не хватает слова «спектакль» везде
- [ ] то же самое про анимацию при наведении на имя, что писала раньше
- [ ] про эту анимацию при наведении на фото что-нибудь сказали? не очень хорошо смотрится, я бы ее все же убрала
- [ ] для актеров без фото добавлю карточку в макет. Хотя все фото есть в инете, можно оттуда брать
- [ ] есть ли возможность добавить такое: чтобы при прокрутке страницы надпись слева «сезон 2020-21» не прокручивалась со страницей, а останавливалась, пока справа прокручивается (например, несколько спектаклей), пока не дойдет до следующего сезона

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/5f0d89249cce1b029e5c4b7e241c034275b56f98
