### ISSUE TITLE
Страница "пресса"

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#29]
[макет](https://www.figma.com/file/tljc3lgdVBKnMoBeg0UHg5/Luna-theatre?node-id=891%3A1435&t=HiQmOpSGdzj8zi79-0)

ToDo:
- [x] десктопная версия
- [x] мобильная версия
- [x] каждая статья открывается в новой вкладке

**так выглядит запрос**: ```/api/press-items?sort[0]=date:desc```

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/tree/press-page
