### ISSUE TITLE
Ссылки на страницы

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#36]
на главной эти элементы должны вести на соотвествующие страницы:
- [x] слайдер спектаклей
- [x] новости 

шапка:
- [x] логотип луны должен вести на главную
- [x] герб москвы и подпись ведут на [сайт мэрии](http://kultura.mos.ru/)

на остальных:
- [x] компонент афиша должен вести на спектакли при нажатии на название

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/982959ca7db81a8e9d523b2d812b0efa457beb14
