### ISSUE TITLE
Страница "контакты"

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#39]
верстка:
- [x] десктоп
- [x] мобильная

**Comment by demig00d** [comment]
Замечания дизайнера
- [ ] сделай, пожалуйста, станции метро в 3 строки, как в макете
- [ ] межстрочное расстояние в заголовках нужно больше, в макете 160%, если в процентах
- [ ] межстрочное в тексте заведующего труппой и ниже тоже неверное везде

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/3d99d770ffc89612f9dd2d48574ef775128632e7

**Comment by demig00d** [comment]
- [ ] в номерах, где написано «(приемная)» нужно другим начертанием текст (в макете)
- [ ] в блоке «билетный стол» в строчке «выходные дни» нужно убрать точку в конце
