### ISSUE TITLE
Кнопка билеты должна вести на якорь

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#41]
эта кнопка в спектакле должна вести на раздел с афишами с той же странице
<img width="996" alt="Screenshot 2022-12-15 at 22 04 18" src="https://user-images.githubusercontent.com/28487425/207961167-5738a224-a856-4350-8437-8932ca02110f.png">

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/805329c297a05e10577700374cf926a36610b178

**Comment by demig00d** [comment]
> 805329c

@Alex-Wolf-front, сделай пожалуйста чтобы заголовок тоже было видно, как на странице маленькая луна

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/f783b9ac5aae035ec4b126a28d9afcb8ad7b9ec0
