### ISSUE TITLE
Шапка мобильной версии

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#44]
![photo_2022-12-16_00-29-32](https://user-images.githubusercontent.com/28487425/207970963-c2788820-e27e-43c3-b4e6-961c2e011207.jpg)

- [x] поменять цвет на ```#08091D``` 
- [x] сделать sticky
- [x] добавить ссылки 
  - [x] афиша
  - [x] спектакли
  - [x] труппа
  - [x] театр
  - [x] новости
  - [x] пресса
  - [x] контакты
  - [x] маленькая луна

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/6edd8f82fa174979e574fabfb4fb8a7d0a93b657
