### ISSUE TITLE
Страница "Труппа"

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#47]
Уточнения:
- [x] все фотки цветные
- [x] добавить ссылки:
  - [x] на Худрука ```/person/35```
  - [x] на Президента ```/person/70```
 - [ ] добавить "титул" людей в сетке (поле ```title``` в json с бэка)
<img width="300" alt="Screenshot 2022-12-16 at 01 32 08" src="https://user-images.githubusercontent.com/28487425/207981294-ece9f05e-9cad-4d5b-b373-ceae789fcc8f.png">

Фиксы:
- [ ] Фикс картинки мобильной версии (она там сейчас прозрачная):
<img src="https://user-images.githubusercontent.com/28487425/207980545-a8d00a40-ac9c-4612-b91b-12a030deecd3.jpg " width="300" />

**Comment by demig00d** [comment]
изменения в API: переименовал категории артистов "актер/актриса" -> "труппа", "режиссёр" -> "режиссёры"

**Comment by demig00d** [comment]
- [ ] лауреат премии «ромашка» вот в таких кавычках (7 скрин)
в блоке информации об актёре разбить на строчки, как в макете **(никак не сделать, так приходит с бэка)**
- [ ] в карточках с постановками в дате месяц верхним регистром нужно (9 скрин)
- [ ] в блоке «роли в кино» сделать левую стрелку неактивным цветом по дефолту

**Comment by EvPanchenko** [comment]
> * [x] у герасимова и проханова другой шрифт стоит, не монтсеррат
> * [x] на этой странице карточки актеров нужно по 4 в ряду
> * [x] по прибытии на имя актера нужно и имя, и фамилию подчеркнуть
> * [x] прокрутку надо убрать
