### ISSUE TITLE
Объединить компоненты PosterEl и PlaysLine

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#48]
Компоненты [PosterEl](https://github.com/tribble-io/luna/blob/8cac8fbd21d10189afbf30a382ab64531b1d597c/src/components/posterContent/posterEl.jsx#L4) и [PlaysLine](https://github.com/tribble-io/luna/blob/8cac8fbd21d10189afbf30a382ab64531b1d597c/src/components/createElement/playsLine/index.js#L4) отличаются только наличием месяца в последнем, необходимо их объединить

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/tree/issues-fix-48
