### ISSUE TITLE
Главная: карточки не листаются при нажатии на последние даты

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#5]
Карточки не листаются при нажатии на 4 или 5 января в красном линейном календаре

запись:

https://user-images.githubusercontent.com/28487425/204603052-21c92124-a2fe-41ba-9bcd-abe241da9c3f.mp4

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/tree/slider-fix
