### ISSUE TITLE
Обновить футер

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#53]
Вот [макет](https://www.figma.com/file/tljc3lgdVBKnMoBeg0UHg5/Luna-theatre?node-id=919%3A42&t=vYM0ePmzRxrfmrTQ-0)

ToDo:
- [x] десктопная версия
- [x] мобильная версия

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/728acb22776fc26feb6c63703c45aa9d1172877a
