### ISSUE TITLE
Поменять слайдер прессы

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#63]
Сделать слайдер прессы как на макете: 
<img width="300" alt="Screenshot 2022-12-16 at 01 32 08" src="https://user-images.githubusercontent.com/28487425/208400944-71b92316-5554-4c09-8f04-06bab4bd7379.jpg">

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/03ce05ca8c8feb18323d39e6a6a5f96b2e4764da
