### ISSUE TITLE
Сетка актеров: имя и фамилия в две строки

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#64]
Имя и фамилия должны быть в две строки:
<img width="700" alt="Screenshot 2022-12-16 at 01 32 08" src="https://user-images.githubusercontent.com/28487425/208401839-6398e56d-6fd7-457a-85b1-a332cf34d866.jpg">

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/c4e3e65a1c7ca84f1d02bcf50f8f80c258d62ec7
