### ISSUE TITLE
Правки для одноэлементных разделов

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#65]
ToDo:
- [x] убрать стрелки
- [x] уменьшить расстояние до следующего элемента

<img width="700" alt="Screenshot 2022-12-16 at 01 32 08" src="https://user-images.githubusercontent.com/28487425/208402865-73ead138-0f74-43c0-85a7-0654ad5c7386.jpg">

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/876ac9847c2178a5b678e117c7e892f5fd3470e1

**Comment by demig00d** [comment]
> 876ac98

- [ ] вернуть третий элемент <img width="700" alt="Screenshot 2022-12-16 at 01 32 08" src="https://user-images.githubusercontent.com/28487425/208720789-6b7bb46c-5ac4-43bf-9aa7-ff015c6e3d9b.jpg">
- [ ] у одногэлементного убрать число страниц <img width="700" alt="Screenshot 2022-12-16 at 01 32 08" src="https://user-images.githubusercontent.com/28487425/208720800-3dfb74de-c751-436a-a1f1-d192a1e5bafc.jpg">

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/commit/7337e4b0620e850841663fc58cbdcb76df935537
