### ISSUE TITLE
Страница актёра

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#66]
ToDo:
- [x] #67 
- [x] #68
- [ ] #69

**Comment by demig00d** [comment]
- [ ] лауреат премии «ромашка» вот в таких кавычках
в блоке информации об актёре разбить на строчки, как в макете **(никак не сделать, так приходит с бэка)**
- [ ] в карточках с постановками в дате месяц верхним регистром нужно 
- [ ] в блоке «роли в кино» сделать левую стрелку неактивным цветом по дефолту

**Comment by EvPanchenko** [comment]
> * [*] лауреат премии «ромашка» вот в таких кавычках 
>   в блоке информации об актере разбить на строчку, как в **макете**
> * [*] в карточках с постановками в дату месяца верхним регистром нужно
> * [*] в блоке «роли в кино» сделать первую стрелку неактивным цветом по дефолту
