### ISSUE TITLE
Страница "главная"

### ISSUE THREAD

**Issue by demig00d** [tribble-io/luna#85]
[макет](https://www.figma.com/file/iFD77wEGzvflypceaAviSo/Untitled?node-id=0%3A1&t=kDPrG0fGahn7eu3Q-0)

чем отличается от текущей главной:
- [x] в большом слайдере надписи со страницы отдельного спектакля (но с плашкой "премьера")
- [x] индикатор (точки) какой спектаклей слайдера показывается
- [x] чуть другие карточки без времени
- [x] pop-up с афишей по нажатию кнопки "билеты"
- [x] опциональный iframe с ютубовским видео
- [x] десктопные новости как здесь https://www.teatroreal.es/en, только с другими цветами
- [x] мобильные новости со страницы "все новости"
- [x] в разделе партнеры iframe c рекомендациями мэрии https://www.mos.ru/otrasli-static/outer/mosTizer.js
- [x] спектакли для большого слайдера, опциональная ссылка на ютуб, как и партнеры теперь приходят с бэка: ```/api/main-page?populate=plays,partners.logo```

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/tree/main-page-new

**Comment by Alex-Wolf-front** [comment]
https://github.com/tribble-io/luna/tree/ticket-popup - popup functional
